# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 115

Metrics/BlockLength:
  Max: 65
  ExcludedMethods: ['describe']
